export const footballClubsData = [
  // Primier League
  {
    name: 'Arsenal',
    logo: 'primierLeague/arsenal.png',
    league: 'Premier League',
    tier: 'Star',
  },
  {
    name: 'Aston Villa',
    logo: 'primierLeague/astonvilla.png',
    league: 'Premier League',
    tier: 'Star',
  },
  {
    name: 'Bournemouth',
    logo: 'primierLeague/bournemouth.png',
    league: 'Premier League',
    tier: 'Low',
  },
  {
    name: 'Brentford',
    logo: 'primierLeague/brentford.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Brighton',
    logo: 'primierLeague/brighton.png',
    league: 'Premier League',
    tier: 'Low',
  },
  {
    name: 'Burnley',
    logo: 'primierLeague/burnley.png',
    league: 'Premier League',
    tier: 'Low',
  },
  {
    name: 'Chelsea',
    logo: 'primierLeague/chelsea.png',
    league: 'Premier League',
    tier: 'Star',
  },
  {
    name: 'Crystal Palace',
    logo: 'primierLeague/crystalpalace.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Everton',
    logo: 'primierLeague/everton.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Fulham',
    logo: 'primierLeague/fulham.png',
    league: 'Premier League',
    tier: 'Low',
  },
  {
    name: 'Liverpool',
    logo: 'primierLeague/liverpool.png',
    league: 'Premier League',
    tier: 'Star',
  },
  {
    name: 'Luton Town',
    logo: 'primierLeague/lutontown.png',
    league: 'Premier League',
    tier: 'Underated',
  },
  {
    name: 'Manchester City',
    logo: 'primierLeague/manchestercity.png',
    league: 'Premier League',
    tier: 'Star',
  },
  {
    name: 'Manchester United',
    logo: 'primierLeague/manchesterunited.png',
    league: 'Premier League',
    tier: 'Star',
  },
  {
    name: 'Newcastle United',
    logo: 'primierLeague/newcastleunited.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Nothingham Forest',
    logo: 'primierLeague/nottinghamforest.png',
    league: 'Premier League',
    tier: 'Underated',
  },
  {
    name: 'Tottenham Hostpur',
    logo: 'primierLeague/tottenhamhostpur.png',
    league: 'Premier League',
    tier: 'Star',
  },
  {
    name: 'Westham United',
    logo: 'primierLeague/westhamunited.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Wolves',
    logo: 'primierLeague/wolves.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Leeds United',
    logo: 'primierLeague/other/leeds.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Leicester City',
    logo: 'primierLeague/other/leicestercity.png',
    league: 'Premier League',
    tier: 'Middle',
  },
  {
    name: 'Norwich City',
    logo: 'primierLeague/other/norwichcity.png',
    league: 'Premier League',
    tier: 'Underated',
  },
  {
    name: 'Southampton F.C',
    logo: 'primierLeague/other/southampton.png',
    league: 'Premier League',
    tier: 'Low',
  },
  {
    name: 'Watford F.C',
    logo: 'primierLeague/other/watford.png',
    league: 'Premier League',
    tier: 'Underated',
  },

  // La Liga
  {
    name: 'Deportivo Alavés',
    logo: 'laLiga/alaves.png',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'Almería',
    logo: 'laLiga/almeria.png',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'Athletic Club',
    logo: 'laLiga/athleticclub.png',
    league: 'La Liga',
    tier: 'Star',
  },
  {
    name: 'Atlético de Madrid',
    logo: 'laLiga/atleticomadrid.png',
    league: 'La Liga',
    tier: 'Star',
  },
  {
    name: 'Barcelona',
    logo: 'laLiga/barcelona.png',
    league: 'La Liga',
    tier: 'Star',
  },
  {
    name: 'Cádiz',
    logo: 'laLiga/cadiz.svg',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'RC Celta de Vigo',
    logo: 'laLiga/celta.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'Getafe FC',
    logo: 'laLiga/getafe.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'Girona',
    logo: 'laLiga/girona.png',
    league: 'La Liga',
    tier: 'Star',
  },
  {
    name: 'Granada FC',
    logo: 'laLiga/granada.png',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'UD Las Palmas',
    logo: 'laLiga/laspalmas.png',
    league: 'La Liga',
    tier: 'Underated',
  },
  {
    name: 'RCD Mallorca ',
    logo: 'laLiga/mallorca.png',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'CA Osasuna',
    logo: 'laLiga/osasuna.png',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'Rayo Vallecano',
    logo: 'laLiga/rayo.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'Real Betis',
    logo: 'laLiga/realbetis.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'Real Madrid',
    logo: 'laLiga/realmadrid.png',
    league: 'La Liga',
    tier: 'Star',
  },
  {
    name: 'Real Sociedad',
    logo: 'laLiga/realsociedad.png',
    league: 'La Liga',
    tier: 'Star',
  },
  {
    name: 'Sevilla',
    logo: 'laLiga/sevilla.png',
    league: 'La Liga',
    tier: 'Star',
  },
  {
    name: 'Valencia CF',
    logo: 'laLiga/valencia.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'Villarreal CF',
    logo: 'laLiga/villarreal.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'Deportivo Alavés',
    logo: 'laLiga/other/deportivo.png',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'Eibar',
    logo: 'laLiga/other/eibar.png',
    league: 'La Liga',
    tier: 'Underated',
  },
  {
    name: 'Elche',
    logo: 'laLiga/other/elche.png',
    league: 'La Liga',
    tier: 'Low',
  },
  {
    name: 'Espanyol',
    logo: 'laLiga/other/espanyol.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'S.D Huesca',
    logo: 'laLiga/other/huesca.png',
    league: 'La Liga',
    tier: 'Underated',
  },
  {
    name: 'Leganés',
    logo: 'laLiga/other/leganés.png',
    league: 'La Liga',
    tier: 'Underated',
  },
  {
    name: 'Levante U.D',
    logo: 'laLiga/other/levante.png',
    league: 'La Liga',
    tier: 'Underated',
  },
  {
    name: 'Malaga C.F',
    logo: 'laLiga/other/malaga.png',
    league: 'La Liga',
    tier: 'Middle',
  },
  {
    name: 'Valladolid',
    logo: 'laLiga/other/valladolid.png',
    league: 'La Liga',
    tier: 'Underated',
  },

  // Seri A
  {
    name: 'A.C Milan',
    logo: 'seriA/acmilan.png',
    league: 'Seri A',
    tier: 'Star',
  },
  {
    name: 'A.S Roma',
    logo: 'seriA/asroma.png',
    league: 'Seri A',
    tier: 'Star',
  },
  {
    name: 'Atalanta',
    logo: 'seriA/atalanta.png',
    league: 'Seri A',
    tier: 'Middle',
  },
  {
    name: 'Bologna',
    logo: 'seriA/bologna.png',
    league: 'Seri A',
    tier: 'Low',
  },
  {
    name: 'Cagliari',
    logo: 'seriA/cagliari.png',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'Empoli FC',
    logo: 'seriA/empoli.png',
    league: 'Seri A',
    tier: 'Low',
  },
  {
    name: 'Fiorentina FC',
    logo: 'seriA/fiorentina.svg',
    league: 'Seri A',
    tier: 'Middle',
  },
  {
    name: 'Frosinone',
    logo: 'seriA/frosinone.png',
    league: 'Seri A',
    tier: 'Low',
  },
  {
    name: 'Genoa',
    logo: 'seriA/genoa.png',
    league: 'Seri A',
    tier: 'Middle',
  },
  {
    name: 'Hellas Verona',
    logo: 'seriA/hellasverona.svg',
    league: 'Seri A',
    tier: 'Low',
  },
  {
    name: 'Intermilan',
    logo: 'seriA/intermilan.png',
    league: 'Seri A',
    tier: 'Star',
  },
  {
    name: 'Juventus',
    logo: 'seriA/juventus.png',
    league: 'Seri A',
    tier: 'Star',
  },
  {
    name: 'S.S Lazio',
    logo: 'seriA/lazio.png',
    league: 'Seri A',
    tier: 'Middle',
  },
  {
    name: 'U.S Lecce',
    logo: 'seriA/lecce.png',
    league: 'Seri A',
    tier: 'Middle',
  },
  {
    name: 'A.C Monza',
    logo: 'seriA/monza.png',
    league: 'Seri A',
    tier: 'Low',
  },
  {
    name: 'Napoli',
    logo: 'seriA/napoli.png',
    league: 'Seri A',
    tier: 'Star',
  },
  {
    name: 'Salernitan',
    logo: 'seriA/salernitan.svg',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'Sassuolo',
    logo: 'seriA/sassuolo.png',
    league: 'Seri A',
    tier: 'Low',
  },
  {
    name: 'Torino FC',
    logo: 'seriA/torino.png',
    league: 'Seri A',
    tier: 'Middle',
  },
  {
    name: 'Udinese Calcio',
    logo: 'seriA/udinese.png',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'Benevento',
    logo: 'seriA/other/benevento.png',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'Brescia',
    logo: 'seriA/other/brescia.png',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'Crotone',
    logo: 'seriA/other/crotone.png',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'Parma',
    logo: 'seriA/other/parma.png',
    league: 'Seri A',
    tier: 'Low',
  },
  {
    name: 'Sampordia',
    logo: 'seriA/other/sampordia.png',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'S.P.A.L',
    logo: 'seriA/other/spal.png',
    league: 'Seri A',
    tier: 'Underated',
  },
  {
    name: 'Venezia',
    logo: 'seriA/other/venezia.svg',
    league: 'Seri A',
    tier: 'Underated',
  },

  //Bundesliga
  {
    name: 'FC Augsburg',
    logo: 'bundesLiga/augsburg.png',
    league: 'Bundesliga',
    tier: 'Low',
  },
  {
    name: 'Bayer Leverkusen',
    logo: 'bundesLiga/bayerleverkusen.png',
    league: 'Bundesliga',
    tier: 'Star',
  },
  {
    name: 'Bayer Munich',
    logo: 'bundesLiga/bayernmunich.png',
    league: 'Bundesliga',
    tier: 'Star',
  },
  {
    name: 'Borussia Dortmund',
    logo: 'bundesLiga/borussiadortmund.png',
    league: 'Bundesliga',
    tier: 'Star',
  },
  {
    name: 'Borussia Mönchengladbach',
    logo: 'bundesLiga/borussiamonchengladbach.png',
    league: 'Bundesliga',
    tier: 'Star',
  },
  {
    name: 'Darmstadt 98',
    logo: 'bundesLiga/damrsradt.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'Eintracht Frankfurt',
    logo: 'bundesLiga/eintracht.png',
    league: 'Bundesliga',
    tier: 'Middle',
  },
  {
    name: 'SC Freiburg',
    logo: 'bundesLiga/freiburg.png',
    league: 'Bundesliga',
    tier: 'Middle',
  },
  {
    name: 'FC Heidenheim',
    logo: 'bundesLiga/heidenheim.svg',
    league: 'Bundesliga',
    tier: 'Low',
  },
  {
    name: '1899 Hoffenheim',
    logo: 'bundesLiga/hoffenheim.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'FC Köln',
    logo: 'bundesLiga/koln.png',
    league: 'Bundesliga',
    tier: 'Low',
  },
  {
    name: 'RB Leipzig',
    logo: 'bundesLiga/leipzing.png',
    league: 'Bundesliga',
    tier: 'Middle',
  },
  {
    name: 'Mainz 05',
    logo: 'bundesLiga/mainz.png',
    league: 'Bundesliga',
    tier: 'Low',
  },
  {
    name: 'Union Berlin',
    logo: 'bundesLiga/unionberlin.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'VfB Stuttgart',
    logo: 'bundesLiga/vfbstuttgart.png',
    league: 'Bundesliga',
    tier: 'Medium',
  },
  {
    name: 'VfL Bochum',
    logo: 'bundesLiga/vflbochum.png',
    league: 'Bundesliga',
    tier: 'Low',
  },
  {
    name: 'VfL Wolfsburg',
    logo: 'bundesLiga/vflwolfsburg.png',
    league: 'Bundesliga',
    tier: 'Star',
  },
  {
    name: 'Werder Bremen',
    logo: 'bundesLiga/werderbremen.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'Arminia Bielefeld',
    logo: 'bundesLiga/other/arminiabielefeld.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'Fortuna Düsseldorf',
    logo: 'bundesLiga/other/fortunadüsseldorf.svg',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'Greuther Fürth',
    logo: 'bundesLiga/other/greutherfürth.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'Hannover 96',
    logo: 'bundesLiga/other/hannover.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'Hertha BSC',
    logo: 'bundesLiga/other/herthabsc.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'FC Nürnberg',
    logo: 'bundesLiga/other/numberg.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'SC Paderborn 07',
    logo: 'bundesLiga/other/paderborn.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
  {
    name: 'FC Schalke 04',
    logo: 'bundesLiga/other/schalke.png',
    league: 'Bundesliga',
    tier: 'Underated',
  },
];
